version: "3.8"
services:

  redis:
    image: redis:alpine
    container_name: redis

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgres/data
    env_file:
      - .env
    container_name: postgres_db

  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_app
    env_file:
      - .env
    command: sh prepare_db.sh 
    depends_on:
      - db

  celery:
    restart: always
    build:
      context: .
    command: 'celery -A core beat -l DEBUG'
    volumes:
      - .:/django
    container_name: celery
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - app

  celery_worker:
    restart: always
    build:
      context: .
    command: 'celery -A core worker -l DEBUG'
    volumes:
      - .:/django
    container_name: celery_worker
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - app
      - celery
