# Generated by Django 3.1.7 on 2022-01-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asset_prices_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('fiat_pair', models.CharField(max_length=30)),
                ('best_bid', models.FloatField()),
                ('best_ask', models.FloatField()),
            ],
        ),
    ]
